#!/usr/bin/env php
<?php
/**
 * @author liyang <liyang@uniondrug.cn>
 * @date   2019-05-06
 */

class Document
{
    public $dbConfig;
    public $authorConfig;
    public $base;

    public function __construct($base)
    {
        $this->base = $base;
        $this->dbConfig = require $base.'/Config/Db.php';
        $this->dbConfig['table'] = $this->getArgvs() ? $this->getArgvs() : $this->dbConfig['table'];
        $this->authorConfig = require $base.'/Config/Author.php';
    }

    public function build()
    {
        $model = new Model($this->dbConfig);
        $columns = $model->build();
        echo 'step 1'.PHP_EOL;
        $constructModel = new ConstructModel($this->dbConfig, $this->authorConfig);
        $constructModel->build($columns);
        echo 'step 2'.PHP_EOL;
        $constructTrait = new ConstructTrait($this->dbConfig, $this->authorConfig);
        $constructTrait->build($columns);
        echo 'step 3'.PHP_EOL;
        $constructRow = new ConstructRow($this->dbConfig, $this->authorConfig);
        $constructRow->build();
        echo 'step 4'.PHP_EOL;
        $constructRows = new ConstructRows($this->dbConfig, $this->authorConfig);
        $constructRows->build();
        echo 'step 5'.PHP_EOL;
        $constructController = new ConstructController($this->dbConfig, $this->authorConfig);
        $constructController->build();
        echo 'step 6'.PHP_EOL;
        $constructService = new ConstructService($this->dbConfig, $this->authorConfig);
        $constructService->build();
        echo 'step 7'.PHP_EOL;
        $constructLogic = new ConstructLogic($this->dbConfig, $this->authorConfig);
        $constructLogic->build();
        echo 'step 8'.PHP_EOL;
        $constructStruct = new ConstructStruct($this->dbConfig, $this->authorConfig);
        $constructStruct->build($columns);
        echo 'step 9'.PHP_EOL;
    }

    /**
     * 处理入参
     */
    private function getArgvs()
    {
        $argvs = $_SERVER['argv'];
        if (count($argvs) > 1) {
            return $argvs[1];
        }
    }
}

spl_autoload_register(function($className){
    require getcwd().'/Parsers/'.$className.'.php';
});
$base = getcwd();
$init = new Document($base);
$init->build();